### ISSUE TITLE
PHP Warnings trying to mysql_close

### ISSUE THREAD

**Issue by mrclay** [brettp/elgg-registration-randomizer#5]
Tons of these in community log: `PHP WARNING: 2015-07-14 20:39:32 (UTC): "mysql_close(): 1 is not a valid MySQL-Link resource" in file /var/www/community.elgg.org/mod/registration_randomizer/start.php (line 81)"`

We should also remove `_elgg_services()` usage.

**Comment by juho-jaakkola** [comment]
Fixed in 278f8b389260c3ad0f1f3a29de0e4767bc06ce74
